#ifndef __metil_configuration_metil_configuration_defaults_h
#define __metil_configuration_metil_configuration_defaults_h

#include <math_c_vector.h>

#define metil_configuration_rendering_properties_default_brightness 1.0
#define metil_configuration_rendering_properties_default_brightness_text 1.0

#define metil_configuration_rendering_properties_default_fps_display 1

#define metil_configuration_rendering_properties_default_colour_fps_display_x 1.0f
#define metil_configuration_rendering_properties_default_colour_fps_display_y 1.0f
#define metil_configuration_rendering_properties_default_colour_fps_display_z 1.0f
#define metil_configuration_rendering_properties_default_colour_fps_display_w 1.0f

struct metil_configuration_rendering_properties_defaults {
  float brightness;
  float brightness_text;

  unsigned char fps_display;
  struct math_c_vector4_float colour_fps_display;

  unsigned char initialized;
};

void metil_configuration_rendering_properties_defaults_initialize(
  struct metil_configuration_rendering_properties_defaults*
);

#endif
