#ifndef __metil_configuration_metil_configuration_defaults_h
#define __metil_configuration_metil_configuration_defaults_h

#include <math_c_vector.h>

#define metil_configuration_rendering_properties_default_brightness 0x01
#define metil_configuration_rendering_properties_default_brightness_text 0x01

#define metil_configuration_rendering_properties_default_fps_display 0x00

#define metil_configuration_rendering_properties_default_colour_fps_display_x 0x01
#define metil_configuration_rendering_properties_default_colour_fps_display_y 0x01
#define metil_configuration_rendering_properties_default_colour_fps_display_z 0x01
#define metil_configuration_rendering_properties_default_colour_fps_display_w 0x01

#define metil_configuration_rendering_properties_default_display_sync 0x01

struct metil_configuration_rendering_properties_defaults {
  float brightness;
  float brightness_text;

  unsigned char fps_display;
  struct math_c_vector4_float colour_fps_display;
  
  unsigned char display_sync;

  unsigned char initialized;
};

void metil_configuration_rendering_properties_defaults_initialize(
  struct metil_configuration_rendering_properties_defaults*
);

#endif
