#include <metil_configuration/configuration_rendering_properties.h>

float metil_configuration_default_rendering_properties_brightness = 1.0f;
float metil_configuration_default_rendering_properties_brightness_text = 1.0f;

unsigned char metil_configuration_default_rendering_properties_fps_display = 0;
