#ifndef __metil_h
#define __metil_h

#include <metil_application/metil_view.h>
#include <metil_application/metil_window.h>
#include <metil_application/metil_view_controller.h>
#include <metil_application/metil_application_delegate.h>
#include <metil_application/metil_nsresponder.h>
#include <metil_application/metil_application.h>
#include <metil_audio/audio.h>
#include <metil_configuration/configuration.h>
#include <metil_configuration/configuration_audio.h>
#include <metil_configuration/configuration_rendering_properties.h>
#include <metil_debug/log.h>
#include <metil_library.h>
#include <metil_menus/menu.h>
#include <metil_menus/menu_item.h>
#include <metil_mesh/mesh.h>
#include <metil_mesh/mesh_box.h>
#include <metil_mesh/mesh_text.h>
#include <metil_initialize.h>
#include <metil_input/controller.h>
#include <metil_input/cursor.h>
#include <metil_input/input.h>
#include <metil_input/keycodes.h>
#include <metil_input/map.h>
#include <metil_object.h>
#include <metil_paths/paths.h>
#include <metil_paths/paths_constants.h>
#include <metil_player.h>
#include <metil_rendering/camera/camera.h>
#include <metil_rendering/camera/lens.h>
#include <metil_rendering/camera/near_far.h>
#include <metil_rendering/metil_renderer.h>
#include <metil_rendering/rendering_properties.h>
#include <metil_scenes/scene.h>
#include <metil_scenes/scene_controller.h>
#include <metil_shader_types.h>
#include <metil_termination.h>
#include <metil_text/text.h>
#include <metil_utilities/stopwatch.h>
#include <metil_utilities/time.h>

#endif
